export const playgrounds = [
  {
    id: "bits",
    title: "Bit tray",
    group: "Signals & symbols",
    invitation: "Flip bits and watch numbers change.",
    topics: "Binary numbers, bitwise operations, Boolean algebra",
  },
  {
    id: "gates",
    title: "Logic bench",
    group: "Signals & symbols",
    invitation: "Wire two gates and trace a signal.",
    topics: "Logic gates, Boolean expressions, circuits",
  },
  {
    id: "encoding",
    title: "Inside a character",
    group: "Signals & symbols",
    invitation: "Enter text and inspect its UTF-8 bytes.",
    topics: "Text encoding, Unicode, UTF-8",
  },
  { id: "bases", title: "Number base tiles", group: "Signals & symbols", invitation: "Build one value, then read it in another base.", topics: "Binary, hexadecimal, number bases, place value" },
  { id: "parity", title: "Parity checker", group: "Signals & symbols", invitation: "Flip a transmitted bit to test parity error detection.", topics: "Parity bits, error detection, data transmission" },
  { id: "compression", title: "Compression blocks", group: "Signals & symbols", invitation: "Arrange repeated symbols and watch runs form.", topics: "Run-length encoding, lossless compression, redundancy" },
  { id: "pixels", title: "Pixel memory", group: "Signals & symbols", invitation: "Paint a tiny image and inspect the bits it occupies.", topics: "Raster graphics, pixels, bitmap encoding" },
  {
    id: "collections",
    title: "Data structure tray",
    group: "Objects & memory",
    invitation: "Add and remove objects; compare how structures behave.",
    topics: "Stacks, queues, sets, arrays, linked lists, abstract data types",
  },
  {
    id: "memory",
    title: "Names & objects",
    group: "Objects & memory",
    invitation: "Copy a value or share an object, then change it.",
    topics: "Variables, memory, references, copying",
  },
  {
    id: "hash",
    title: "Hash buckets",
    group: "Objects & memory",
    invitation: "Add keys that map to the same hash bucket.",
    topics: "Hash tables, chaining, hashing",
  },
  {
    id: "cache",
    title: "Memory playground",
    group: "Objects & memory",
    invitation: "Access memory addresses to test cache hits and eviction.",
    topics: "Cache, locality, LRU replacement",
  },
  { id: "arrays", title: "Array insertion", group: "Objects & memory", invitation: "Choose a slot and make room for a new value.", topics: "Arrays, insertion, indexed storage, shifting" },
  { id: "linked", title: "Linked nodes", group: "Objects & memory", invitation: "Cut and reconnect pointers without moving the nodes.", topics: "Linked lists, pointers, traversal" },
  { id: "unionfind", title: "Union-find forest", group: "Objects & memory", invitation: "Join groups, then ask whether two objects connect.", topics: "Disjoint sets, union-find, connectivity" },
  { id: "heap", title: "Heap tree", group: "Objects & memory", invitation: "Insert values and track the minimum at the root.", topics: "Binary heaps, priority queues, heap invariant" },
  { id: "tree", title: "Search tree garden", group: "Objects & memory", invitation: "Insert values and trace the binary search path.", topics: "Binary search trees, insertion, search" },
  { id: "gc", title: "Reachability collector", group: "Objects & memory", invitation: "Remove a root and see which objects become collectible.", topics: "Garbage collection, reachability, roots" },
  { id: "paging", title: "Page-frame mapper", group: "Objects & memory", invitation: "Translate virtual addresses and replace pages in memory.", topics: "Virtual memory, pages, frames, page faults" },
  {
    id: "graph",
    title: "Graph explorer",
    group: "Paths & algorithms",
    invitation: "Connect nodes and compare the paths through your graph.",
    topics: "Breadth-first search, depth-first search, graphs",
  },
  {
    id: "sorting",
    title: "Sorting bench",
    group: "Paths & algorithms",
    invitation: "Rearrange the bars, then compare how algorithms sort them.",
    topics: "Bubble sort, insertion sort, merge sort, quicksort, complexity",
  },
  {
    id: "hanoi",
    title: "Towers of Hanoi",
    group: "Paths & algorithms",
    invitation: "Move the tower, one disk at a time.",
    topics: "Recursion, planning, Towers of Hanoi",
  },
  { id: "binarysearch", title: "Binary search window", group: "Paths & algorithms", invitation: "Pick a target and halve the search space yourself.", topics: "Binary search, divide and conquer, sorted arrays" },
  { id: "maze", title: "Maze frontier", group: "Paths & algorithms", invitation: "Place walls and grow a search frontier toward the goal.", topics: "Maze search, breadth-first search, frontiers" },
  { id: "shortest", title: "Weighted path map", group: "Paths & algorithms", invitation: "Change a road cost and reroute the shortest trip.", topics: "Dijkstra, weighted graphs, shortest paths" },
  { id: "recursion", title: "Recursion stack", group: "Paths & algorithms", invitation: "Push calls, then unwind their returned values.", topics: "Recursion, call stack, factorial" },
  { id: "dynamic", title: "Coin-change board", group: "Paths & algorithms", invitation: "Choose coin values and calculate the fewest coins for each total.", topics: "Dynamic programming, memoization, coin change" },
  { id: "knapsack", title: "Knapsack tray", group: "Paths & algorithms", invitation: "Pack value without crossing the weight limit.", topics: "Knapsack problem, optimization, constraints" },
  { id: "stringmatch", title: "Pattern window", group: "Paths & algorithms", invitation: "Slide a pattern across text until every symbol matches.", topics: "String matching, substring search, comparisons" },
  {
    id: "threads",
    title: "Be the scheduler",
    group: "Systems you can interrupt",
    invitation: "Choose which thread runs. Can you lose an update?",
    topics: "Concurrency, race conditions, locks, synchronization",
  },
  {
    id: "deadlock",
    title: "Resource tug-of-war",
    group: "Systems you can interrupt",
    invitation: "Give out resources and create a circular wait.",
    topics: "Deadlock, resource ownership, recovery",
  },
  {
    id: "packets",
    title: "Packet playground",
    group: "Systems you can interrupt",
    invitation: "Send packets, cut a link, and fill a queue.",
    topics: "Packet switching, networks, queues, packet loss",
  },
  {
    id: "quorum",
    title: "A cluster agrees",
    group: "Systems you can interrupt",
    invitation: "Disconnect peers and deliver acknowledgements.",
    topics: "Raft quorum, replication, distributed consensus",
  },
  { id: "pipeline", title: "CPU pipeline lane", group: "Systems you can interrupt", invitation: "Feed instructions, add a stall, and watch the lane fill.", topics: "CPU pipeline, hazards, stalls, instruction throughput" },
  { id: "scheduler", title: "Process scheduler", group: "Systems you can interrupt", invitation: "Give CPU slices and compare who finishes first.", topics: "Process scheduling, round robin, shortest job first" },
  { id: "filesystem", title: "File block shelf", group: "Systems you can interrupt", invitation: "Allocate files into fragmented disk blocks.", topics: "File systems, allocation, fragmentation" },
  { id: "branch", title: "Branch predictor", group: "Systems you can interrupt", invitation: "Choose branch outcomes and train a tiny predictor.", topics: "Branch prediction, saturating counters, CPU" },
  { id: "dns", title: "DNS relay", group: "Systems you can interrupt", invitation: "Pass a name request through each resolver.", topics: "DNS resolution, caching, recursive lookup" },
  { id: "loadbalance", title: "Load balancer", group: "Systems you can interrupt", invitation: "Send requests, drain servers, and take one offline.", topics: "Load balancing, server health, least connections" },
  { id: "tcp", title: "Congestion window", group: "Systems you can interrupt", invitation: "Deliver acknowledgements, then trigger packet loss.", topics: "TCP congestion control, congestion window, loss" },
  {
    id: "transactions",
    title: "Crash a transaction",
    group: "Data & decisions",
    invitation: "Move funds, commit, or crash the working copy.",
    topics: "ACID, atomicity, durability, transactions",
  },
  {
    id: "joins",
    title: "Join the tables",
    group: "Data & decisions",
    invitation: "Change matching keys and connect two collections.",
    topics: "Relational joins, inner join, left join, databases",
  },
  {
    id: "automaton",
    title: "Build a recognizer",
    group: "Data & decisions",
    invitation: "Rewire transitions and feed your machine a word.",
    topics: "Finite state machines, automata, formal languages",
  },
  { id: "btree", title: "B-tree shelf", group: "Data & decisions", invitation: "Insert keys and split an overfull node.", topics: "B-tree indexes, node splitting, database indexes" },
  { id: "queryplan", title: "Query plan builder", group: "Data & decisions", invitation: "Choose a scan path and compare the work it causes.", topics: "Query planning, indexes, nested-loop join, cost" },
  { id: "decisiontree", title: "Decision split", group: "Data & decisions", invitation: "Move a threshold and watch examples change sides.", topics: "Decision trees, classification, thresholds" },
  { id: "neuralnet", title: "Tiny neuron", group: "Data & decisions", invitation: "Toggle inputs and tune a weight until the neuron fires.", topics: "Neural networks, weights, bias, perceptron" },
  { id: "reinforcement", title: "Reward path", group: "Data & decisions", invitation: "Move an agent, set rewards, and update what it expects.", topics: "Reinforcement learning, Q-learning, rewards" },
  { id: "access", title: "Permission workshop", group: "Data & decisions", invitation: "Give a role a resource and test the access decision.", topics: "Access control, roles, permissions, least privilege" },
  {
    id: "gradient",
    title: "Find the valley",
    group: "Data & decisions",
    invitation: "Place a point, take a step, and try overshooting.",
    topics: "Gradient descent, learning rate, optimization",
  },
  {
    id: "crypto",
    title: "Keys & a public channel",
    group: "Signals & symbols",
    invitation: "Choose private keys and exchange public values.",
    topics: "Diffie-Hellman, modular arithmetic, public-key exchange",
  },
] as const;
export type PlaygroundId = (typeof playgrounds)[number]["id"];
export const playgroundById = Object.fromEntries(
  playgrounds.map((p) => [p.id, p]),
) as Record<PlaygroundId, (typeof playgrounds)[number]>;
